@startuml login
start
:<Ввод логина и пароля>;
:Получение из БД списка логинов]
if (Введённый логин есть в системе?) then (Да)
  :Получение из БД хешированного пароля по этому логину]
  :Хеширование введённого пароля]
  if (Хеши паролей совпадают?) then (Да)
    :Получение из БД роли этого аккаунта]
    :Успешная авторизация с правами этой роли]
    :<Вывод меню>;
  else (Нет)
    :<Вывод ошибки: неверные данные>;
  endif
else (Нет)
  :<Вывод ошибки: неверные данные>;
endif
stop
@enduml